server:
  port: 60090
dubbo:
  application:
    name: sys-consumer
    owner: programmer
    organization: dubbox
  registry:
    address: zookeeper://localhost:2181
  scan: cn.zhangjingyao.controller
#pageHaleper 配置
pagehelper:
  #pageNum<=0 会查询第一页，如果 pageNum>总页数 会查询最后一页
  reasonable: true